### ISSUE TITLE
Sistema de guardado para reemplazar muerte

### ISSUE THREAD

**Issue by DiegoCaballeroRuiz** [Proyectos1-FDI-UCM/c2324-Grupo02#19]

**Comment by ghost** [comment]
- [x] Se serializan cualesquiera tipos de datos heterogéneos a .json
- [x] Se guardan todos los bytes de terreno codificados en un formato con un buen tradeoff de compresión-velocidad de RW

**Comment by ghost** [comment]
Se guardan todos los bytes de terreno codificados en un formato con un buen tradeoff de compresión-velocidad de RW: **.qoi**
